import type { Metadata } from "next";
import { Lato, Plus_Jakarta_Sans, Pacifico } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-plus-jakarta",
});

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-pacifico",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${lato.variable} ${plusJakarta.variable} ${pacifico.variable}`}
    >
      <body className="font-lato bg-brand-secondary">
        <Header />

        {children}
      </body>
    </html>
  );
}
